# Generated by Django 4.2.3 on 2023-09-09 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie_Produit',
            fields=[
                ('id_cat', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Catégorie Produit',
                'verbose_name_plural': 'Catégories Produit',
                'db_table': 'tCategorie',
                'ordering': ['id_cat'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_cmd', models.AutoField(primary_key=True, serialize=False)),
                ('etat_cmd', models.CharField(choices=[('en_attente', 'En Attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'db_table': 'tCommande',
                'ordering': ['date_ajout'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id_liv', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('postnom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.CharField(max_length=200)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, upload_to='Photo_Livreur/')),
            ],
            options={
                'verbose_name': 'Livreur',
                'verbose_name_plural': 'Livreurs',
                'db_table': 'tLivreur',
                'ordering': ['date_ajout'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('prix_unitaire', models.FloatField(default=0.0)),
                ('description', models.TextField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='images_produits/')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecom.categorie_produit')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'db_table': 'tproduit',
                'ordering': ['date_ajout'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id_Vente', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_total', models.FloatField(editable=False)),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecom.produit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'db_table': 'tVente',
                'ordering': ['date_vente'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.AutoField(primary_key=True, serialize=False)),
                ('stock_dispo', models.PositiveIntegerField()),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Ecom.produit')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'db_table': 'tSock',
                'ordering': ['id_stock'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vente', models.ManyToManyField(to='Ecom.vente')),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('etat_livraison', models.CharField(choices=[('livre', 'Livré'), ('en_attente', 'En Attente'), ('echec', 'Echec')], default='en_attente', max_length=20)),
                ('date_livraison', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecom.commande')),
                ('livreur', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Ecom.livreur')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'db_table': 'tLivraison',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='livreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ecom.livreur'),
        ),
        migrations.AddField(
            model_name='commande',
            name='vente',
            field=models.ManyToManyField(to='Ecom.vente'),
        ),
        migrations.CreateModel(
            name='Approvisionnement',
            fields=[
                ('id_approv', models.AutoField(primary_key=True, serialize=False)),
                ('quantite_approv', models.PositiveIntegerField()),
                ('date_approv', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecom.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Approvisionnement',
                'verbose_name_plural': 'Approvisionnements',
                'db_table': 'tApprovisionnement',
                'ordering': ['date_approv'],
                'managed': True,
            },
        ),
    ]
