# Generated by Django 4.2.3 on 2023-09-10 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0003_alter_vente_date_vente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecom.produit'),
        ),
    ]
