# Generated by Django 4.2.3 on 2023-09-10 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0004_alter_stock_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='produit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Ecom.produit'),
        ),
    ]
