# Generated by Django 4.2.3 on 2023-09-14 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0005_alter_stock_produit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Panier',
        ),
    ]
