# Generated by Django 4.2.3 on 2023-09-29 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0008_alter_commande_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='vente',
        ),
        migrations.AddField(
            model_name='commande',
            name='vente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Ecom.vente', verbose_name='Vente'),
            preserve_default=False,
        ),
    ]
