# Generated by Django 4.2.3 on 2023-09-29 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0009_remove_commande_vente_commande_vente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='client',
        ),
    ]
