# Generated by Django 4.2.3 on 2023-09-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0010_remove_commande_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
