# Generated by Django 4.2.3 on 2023-10-13 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0011_alter_commande_date_ajout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='livreur',
        ),
    ]
