# Generated by Django 4.2.3 on 2023-10-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0012_remove_commande_livreur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='etat_livraison',
            field=models.CharField(choices=[('Livré', 'Livré'), ('En Attente', 'En Attente'), ('Echec', 'Echec')], default='en_attente', max_length=20),
        ),
    ]
