# Generated by Django 4.2.3 on 2023-10-13 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0013_alter_livraison_etat_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='livreur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Ecom.livreur'),
        ),
    ]
