# Generated by Django 4.2.3 on 2023-10-13 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0014_commande_livreur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='livreur',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Ecom.livreur'),
        ),
    ]
