# Generated by Django 4.2.3 on 2023-10-13 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0015_alter_commande_livreur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='livreur',
        ),
    ]
