# Generated by Django 4.2.3 on 2023-10-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0016_remove_livraison_livreur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='etat_livraison',
            field=models.CharField(default='En Attente', max_length=20),
        ),
    ]
