# Generated by Django 4.2.3 on 2023-10-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0018_alter_commande_vente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='vente',
        ),
        migrations.AddField(
            model_name='commande',
            name='vente',
            field=models.ManyToManyField(to='Ecom.vente'),
        ),
    ]
