# Generated by Django 4.2.3 on 2023-10-13 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ecom', '0019_remove_commande_vente_commande_vente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='vente',
        ),
        migrations.AlterField(
            model_name='vente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commande',
            name='vente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Ecom.vente', verbose_name='Vente'),
            preserve_default=False,
        ),
    ]
