# Generated by Django 4.2.3 on 2023-10-13 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ecom', '0020_remove_commande_vente_alter_vente_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
