# Generated by Django 4.2.3 on 2023-10-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0021_alter_vente_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='etat_cmd',
            field=models.CharField(default='En Attente', max_length=20),
        ),
    ]
