# Generated by Django 4.2.3 on 2023-10-15 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0022_alter_commande_etat_cmd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='livreur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecom.livreur'),
        ),
    ]
