# Generated by Django 4.2.3 on 2023-10-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0024_alter_stock_stock_dispo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='id_Vente',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
