# Generated by Django 4.2.3 on 2023-10-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0025_alter_vente_id_vente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='id_Vente',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
