from django.urls import path
from .views import *
from Accounts.views import register_view, login_view, logout_view, all_users, user_details, user_profile

urlpatterns = [
    path('', index, name="index"),
    path('register/', register_view, name="signup"),
    path('login/', login_view, name="login"),
    path('login_deliver/', deliver_connection, name="deliver_login"),
    path('logout/', logout_view, name="logout"),
    path('produit/<str:slug>/', detail_produit, name="detail"),
    path('add-to-cart/', add_to_cart, name="add-to-cart"),
    path('cart/', cart, name="cart"),
    path('update-cart/', update_cart, name="update-cart"),
    path('delete-from-cart/', delete_from_cart, name="delete-from-cart"),
    path('vente/', sales, name="vente"),
    path('commande/', orders, name="commande"),
    path('get-commande/<int:id_cmd>', get_order, name="get-commande"),
    path('update-commande/<int:id_cmd>', update_order, name="update-commande"),
    path('administration/', administration, name="administration"),
    path('page-404/', page_not_found, name="page-404"),
    path('approvisionnement/', create_approvisionnement, name="approvisionnement"),
    path('all-users/', all_users, name="all-users"),
    path('user-profile/<int:id>', user_profile, name="user-profile"),
    path('user-details/<int:id>', user_details, name="user-details"),
    path('delivers/', delivers, name="delivers"),
    path('deliver-details/<int:id_liv>', deliver_details, name="deliver-details"),
    path('display-product/', display_products, name="display-product"),
    path('add-product/', add_product, name="add-product"),
    path('update-product/<int:id_prod>', update_product, name="update-product"),
    path('record-update-product/<int:id_prod>', record_update_product, name="record-update-product"),
    path('delete-product/<int:id_prod>', delete_product, name="delete-product"),
    path('add-category/', add_categorie, name="add-category"),
    path('get-category/<int:id_cat>', get_categorie, name="get-category"),
    path('update-category/<int:id_cat>', update_categorie, name="update-category"),
    path('delete-category/<int:id_cat>', delete_categorie, name="delete-category"),
    path('stock/', stock_view, name="stock"),
    path('vente-ajout/', create_vente, name="vente-ajout"),
    path('checkout/', checkout, name='checkout_payment'),
    path('livraison/', livraison, name='livraison'),
    path('get-livraison/<int:id>', get_livraison, name='get-livraison'),
    path('confirmer-livraison/<int:id>', confirmer_livraison, name='confirmer-livraison'),
    path('get-invoice/', invoice, name='get-invoice'),
    path('restart-cart/', restart, name='restart-cart'),
    path('complete/', payment_success, name='complete'),
]
